//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace registar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisitorLog
    {
        public int LogId { get; set; }
        public int VisitorId { get; set; }
        public Nullable<System.DateTime> CheckInTime { get; set; }
        public Nullable<System.DateTime> CheckOutTime { get; set; }
        public string Remarks { get; set; }
    
        public virtual Visitor Visitor { get; set; }
    }
}
