//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace registar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visitor
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Purpose { get; set; }
        public System.DateTime VisitDate { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public System.Guid GroupId { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> RegisteredAt { get; set; }
        public string IdPassPath { get; set; }
    
        public virtual Department Department { get; set; }
    }
}
